### ISSUE TITLE
Errors using myproxyclient on linux mint 17.3 via anaconda python

### ISSUE THREAD

**Issue by bnlawrence** [philipkershaw/MyProxyClient#7]
```
$myproxyclient logon -s myproxy.ceda.ac.uk -b -C ~/.esg/certificates -o ~/.esg/credentials.pem -l lawrenceEnter password for user 'lawrence' on MyProxy server 'myproxy.ceda.ac.uk':
Traceback (most recent call last):
  File "/home/bnl/anaconda2/bin/myproxyclient", line 9, in <module>
    load_entry_point('MyProxyClient==2.0.1', 'console_scripts', 'myproxyclient')()
  File "/home/bnl/anaconda2/lib/python2.7/site-packages/MyProxyClient-2.0.1-py2.7.egg/myproxy/script.py", line 196, in main
    do_logon(myproxy, options)
  File "/home/bnl/anaconda2/lib/python2.7/site-packages/MyProxyClient-2.0.1-py2.7.egg/myproxy/script.py", line 221, in do_logon
    updateTrustRoots=options.trustroots)
  File "/home/bnl/anaconda2/lib/python2.7/site-packages/MyProxyClient-2.0.1-py2.7.egg/myproxy/client.py", line 1448, in logon
    **getTrustRootsKw)
  File "/home/bnl/anaconda2/lib/python2.7/site-packages/MyProxyClient-2.0.1-py2.7.egg/myproxy/client.py", line 1605, in getTrustRoots
    conn.write(self.__class__.GLOBUS_INIT_MSG)
  File "/home/bnl/anaconda2/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1256, in send
    self._raise_ssl_error(self._ssl, result)
  File "/home/bnl/anaconda2/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1166, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')
```

**Comment by bnlawrence** [comment]
(I should say it would be tidier to trap all that stuff and only provide it if it was invoked with an option to request it ... it should fail gracefully rather than do the python equivalent of a stack dump :-)

**Comment by philipkershaw** [comment]
I agree. :) I'm developing MyProxyClient from cedadev these days: https://github.com/cedadev/MyProxyClient

The myproxy server for CEDA is now ``slcs1.ceda.ac.uk``.  We will be retiring this also not too long in the future and replacing with web service equivalent ``ContrailOnlineCAClient``.  Call is something like:
```
$ online-ca-client get_trustroots https://slcs.ceda.ac.uk/onlineca/trustroots/ -s -b -c ~/.esg/certificates
$ online-ca-client get_cert -s https://slcs.ceda.ac.uk/onlineca/certificate/ -l <username> -c ~/.esg/certificates -o ~/.esg/credentials.pem
```

**Comment by philipkershaw** [comment]
Patched in https://github.com/cedadev/MyProxyClient/tree/devel/myproxy

You won't get a strack trace unless you explicitly set `-e` option
