### ISSUE TITLE
Error importing `from myproxy.client import MyProxyClient` with Python=3.12 due to SafeConfigParser being completely retired

### ISSUE THREAD

**Issue by valeriupredoi** [philipkershaw/MyProxyClient#9]
Hi Phil, how's things? We're moving on to Python=3.12 and noticed an issue with pyesgf client that uses MyProxyClient, that buils down to an import issue:

```
from myproxy.client import MyProxyClient
```

spits out:
```
Traceback (most recent call last):
  File "/home/valeriu/ESMValCore/testimp.py", line 1, in <module>
    from myproxy.client import MyProxyClient
  File "/home/valeriu/miniconda3/envs/esmvaltool-fromlock/lib/python3.12/site-packages/myproxy/client/__init__.py", line 44, in <module>
    from myproxy.client.utils.openssl import OpenSSLConfig
  File "/home/valeriu/miniconda3/envs/esmvaltool-fromlock/lib/python3.12/site-packages/myproxy/client/utils/__init__.py", line 11, in <module>
    from six.moves.configparser import SafeConfigParser
ImportError: cannot import name 'SafeConfigParser' from 'configparser' (/home/valeriu/miniconda3/envs/esmvaltool-fromlock/lib/python3.12/configparser.py). Did you mean: 'RawConfigParser'?
```

I am using `six=1.16` and `myproxyclient=2.1.0`. As far as I can see `SafeConfigParse` was renamed to `ConfigParser` many moons ago https://github.com/benjaminp/six/issues/218 but only now it has been completely nuked https://docs.python.org/3/whatsnew/3.12.html - I can open a PR fix this here if you OK with that? Many thanks and cheers :beer:

**Comment by valeriupredoi** [comment]
my apologies, I opened a new Issue on the new repo https://github.com/cedadev/MyProxyClient/issues/19
